workers: 4
debug: True

classification:
  vgg16:
    img_path: 'data/kaggle_mri_classification/brain_tumor_dataset/'
    split_path: 'data/kaggle_mri_classification/preprocessing_data/'
    train_dir: 'data/kaggle_mri_classification/preprocessing_data/train/'
    test_dir: 'data/kaggle_mri_classification/preprocessing_data/test/'
    val_dir: 'data/kaggle_mri_classification/preprocessing_data/val/'
    train_dir_crop: 'data/kaggle_mri_classification/preprocessing_data/train_crop/'
    test_dir_crop: 'data/kaggle_mri_classification/preprocessing_data/test_crop/'
    val_dir_crop: 'data/kaggle_mri_classification/preprocessing_data/val_crop/'
    vgg16_weights: 'data/kaggle_mri_classification/vgg16_weights/vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5'
    result_classification: 'data/kaggle_mri_classification/results_classification/'