workers: 4
debug: True

classification:
  vgg16:
    img_path: 'data/kaggle_mri_classification/brain_tumor_dataset/'
    split_path: 'data/kaggle_mri_classification/'
    train_dir: 'data/kaggle_mri_classification/train/'
    test_dir: 'data/kaggle_mri_classification/test/'
    val_dir: 'data/kaggle_mri_classification/val/'
    train_dir_crop: 'data/kaggle_mri_classification/train_crop/'
    test_dir_crop: 'data/kaggle_mri_classification/test_crop/'
    val_dir_crop: 'data/kaggle_mri_classification/val_crop/'
    vgg16_weights: 'data/kaggle_mri_classification/vgg16_weights/2019-06-07_VGG_model.h5'